### ISSUE TITLE
 [::] opkeyclass = 2

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/ledokol#10]
Слетает периодически ключ у VIP`ов. Повторить не смог... то слетает, то нет, непонятно.

**Comment by RoLex** [comment]
Вот именно, какой ты клиент используешь, при каких условиях это происходит, какая версия хаба и ледокола, какие настройки у хаба и ледокола - нихера не понятно. Подождем пока тебе станет понятно.

**Comment by sirtrifanoff** [comment]
Версия хаба и ледокола всегда последние (dev). Стабильно пропадает у випа с греем, при каких условиях у него пропадает - без понятия. Какие конкретно настройки хаба и ледокола нужны?

**Comment by RoLex** [comment]
На выходных перекину этот функционал в верлик. Эта функция в ледоколе тоже "липовая" - юзер как будто добавляется в оплист, но на самом деле это только визуально, физически он остается вне оплиста. В таких условиях любое полное обновление юзерлиста грозит потерей ключа - именно это и есть твоя проблема.

**Comment by RoLex** [comment]
> !ledoset opkeyclass 11
> !set oplist_class 2

**Comment by sirtrifanoff** [comment]
Отлично, спасибо.
