### ISSUE TITLE
 [::] enablecmdlog = 1

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/ledokol#11]
Обратил внимание, что !clog не запоминает такие команды как +history от юзеров 0 класса, !kick от випов, возможно, что еще что то не запоминает.

**Comment by RoLex** [comment]
```
[19:33:13 | RU] <RoLex> !clog 25
[19:33:14] <# Test> Showing 25 entries from command logger:

 10/12 19:33: [10] <RoLex> !clog 25
 10/12 19:33: [00] <Tester> +history 10
 10/12 19:32: [10] <RoLex> !rdel Tester
 10/12 19:32: [10] <RoLex> !clog 25
 10/12 19:32: [02] <Tester> +kick Xjoker Test
 10/12 19:32: [10] <RoLex> !ledoset enablevipkick 1
 10/12 19:31: [10] <RoLex> !rn Tester 2 123
...
```

**Comment by sirtrifanoff** [comment]
У меня стабильно повторяется. Думал про настройку какую забыл, которая пишет cmd определенных классов, так нет вроде такой. Потом попробовал выключить/включить  [*] unknown_cmd_chat думал оно влияет, без изменений. Вот мои настройки хаба и ледо, авось поможет https://pastebin.com/9hbixK6Q   https://pastebin.com/1PQ4wukY

**Comment by RoLex** [comment]
!ledoset enablecmdlog 2

**Comment by sirtrifanoff** [comment]
Во блин, всегда думал, что enablecmdlog умеет только 0/1 Спасибо.
