### ISSUE TITLE
+nick

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/ledokol#12]
випам разрешено  [::] custnickclass = 2 но нет уведомления 10му классу кто из випов использовал  команду +nick.

**Comment by RoLex** [comment]
В главном чате приходит оповещение всем кто `>= classnoticust`.

**Comment by sirtrifanoff** [comment]
да, в главном есть, вот такого вида. `<Аранк> KCAHDEP теперь известен как: 123`. я сначала подумал что кто то из випов или опов изменил ник другому випу, так как не увидел уведомление о использованной команде. полез смотреть `clog` и там уже увидел, что вип сам себе сменил использовав команду `+nick` поэтому и написал, что нет уведомлений.

**Comment by sirtrifanoff** [comment]
у меня еще вопрос про заглушки. можно как то разрешить випам заглушки? (конкретно `+gag nick` с установленным временем по умолчанию, как у `tban_kick` без `gagipadd` и `gagccadd`) или это можно будет сделать когда ты перенесешь полностью все заглушки в верли как собирался? просто наклепали кучу випов и они теперь просят к кику разрешить заглушку))

**Comment by RoLex** [comment]
Готово.

Ты:

```
!maykick <nick> 3d
```

Вип:

```
+vipgag <nick>
+vipungag <nick>
```

**Comment by sirtrifanoff** [comment]
клёво, спасибо.
