### ISSUE TITLE
syslog warn mysql

### ISSUE THREAD

**Issue by ghost** [Verlihub/ledokol#2]
Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. The statement is unsafe because it uses a LIMIT clause. This is unsafe because the set of rows included cannot be predicted. Statement: update `lua_ledo_rem` set `timer` = 205 where `id` = '1' limit 1

**Comment by RoLex** [comment]
What kind of binary log are you talking about? Where did you take that information from? This query will always update one row because it uses `id = '1'`. `limit 1` is not needed there, I know. But what is so unsafe about it? I don't understand.
