### ISSUE TITLE
не видно кто и какую команду использовал.

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/ledokol#3]
пример. <бот> [02] Пользователь oakley с IP-адресом 95.26.132.158.RU 0-го класса был кикнут: <бот> Нет указанных причин - видно что был кик, а кто кикнул то? не показано кто и какую команду ввел. показ вводимых команд включен. знаю что ктото из випов
 .:: Статистика Ledokol:

 Версия скрипта: 2.9.4.58.RU
 Версия Verlihub: 1.0.4.5
 Версия плагина Lua: 1.3.0.6
 Версия библиотек Lua: 5.3.4
 Версия модуля LuaSocket: 3.0-rc1
 Версия MySQL: 10.1.25-MariaDB-1~xenial
 Версия cURL: 7.47.0

**Comment by RoLex** [comment]
`<бот>` Нет указанных причин

Без причин - кик на config.tban_kick

**Comment by sirtrifanoff** [comment]
<бот> Нет указанных причин - имя бота указано, а не ник того кто кикнул.
если кикает вип то <бот> [02] Пользователь ёунигаз с IP-адресом 95.26.184.98.RU 0-го класса был кикнут: <бот> Нет указанных причин
если кикает оператор то <бот> [02] Пользователь март с IP-адресом 5.44.169.188.RU 0-го класса был кикнут: <никоператора> Нет указанных причин
нет показа для kick.пример - Пользователь Delphi с IP адресом 46.243.142.20.BG и классом 3 использовал следующую команду: !ipinfo  5.44.169.188

**Comment by RoLex** [comment]
Я сначала не знал что речь о вип киках. Добавил оповещение команды.
