### ISSUE TITLE
автозамена

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/ledokol#4]
доброго времени. я знаю что, любые ссылки можно писать оператору в личку (в обход антирекламы), но автозамена рабоатет и на лички операторам. можно поправить такую реакцию и на автозамену?

**Comment by RoLex** [comment]
Да, реклама проходит операторам если включено, allowspamtoops = 1. Добавил тоже самое только для автозамены, norepltoops = 1.

**Comment by sirtrifanoff** [comment]
принято
