### ISSUE TITLE
gag&geo

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/ledokol#5]
как скоро можно ожидать заглушку по городу и автообновление гео баз без перезагрузки хаба?

**Comment by RoLex** [comment]
Готово, обнови и то и другое. Перезагрузка баз через команду reload.

**Comment by sirtrifanoff** [comment]
даю !reload из чата и хаб падает, вернее рестартует
[10:00:38] <bot> Done reloading all lists and databases.
[10:00:39] *** Cоединение закрыто

**Comment by RoLex** [comment]
Я не ясновидящий, так что давай все логи краха.

**Comment by sirtrifanoff** [comment]
Error Traversing Database for ipnum = 3156482062 - Perhaps database is corrupt?
 (0)                           2017-09-04 17:00:38 #                main - Received a 11 signal, doing stacktrace and quiting
 (0)                           2017-09-04 17:00:38 #                cServerDC - Stack backtrace:

/usr/local/bin/verlihub: mySigServHandler(int) +0x93
/lib/x86_64-linux-gnu/libc.so.6: () +0x354b0
/usr/lib/x86_64-linux-gnu/libGeoIP.so.1: GeoIP_id_by_name_gl() +0x97
/usr/lib/x86_64-linux-gnu/libGeoIP.so.1: GeoIP_country_code_by_name_gl() +0x9
/usr/lib/x86_64-linux-gnu/libGeoIP.so.1: GeoIP_country_code_by_name() +0x1c
/usr/local/lib/libverlihub.so: nVerliHub::nUtils::cGeoIP::GetCC(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) +0x14f
/usr/local/lib/libverlihub.so: nVerliHub::nSocket::cDCConnFactory::CreateConn(int) +0x96
/usr/local/lib/libverlihub.so: nVerliHub::nSocket::cAsyncConn::Accept() +0x89
/usr/local/lib/libverlihub.so: nVerliHub::nSocket::cAsyncSocketServer::TimeStep() +0x1d3
/usr/local/lib/libverlihub.so: nVerliHub::nSocket::cAsyncSocketServer::run() +0xe8
/usr/local/bin/verlihub: main() +0x580
/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main() +0xf0
/usr/local/bin/verlihub: _start() +0x29

 (0)                           2017-09-04 17:00:38 #                cServerDC - Successfully sent stack backtrace to crash server

**Comment by RoLex** [comment]
Мерси. На выходных исправлю.

**Comment by sirtrifanoff** [comment]
отлично, спасибо. может тогда как вариант, сделаешь по команде !reload не только перезагрузку базы, но и ее скачивание и дальнейшее обновление, без перезагрузки? или ты так уже и сделал... а то получается сначала лезешь в консоль, делаешь vh -g потом !reload...

**Comment by RoLex** [comment]
Нет, из хаба не буду выполнять команды консоли, это не безопасно. Могу написать отдельный скрипт на Луа в 10 строк.

**Comment by sirtrifanoff** [comment]
не люблю плодить кучу скриптов. пусть будет как ты задумал.

**Comment by RoLex** [comment]
Чтото не могу повторить падение. Можешь расшарить базу GeoIP.dat с которой у тебя падает хаб? И еще, кто кидает сообщение "Error Traversing Database for ipnum = 3156482062 - Perhaps database is corrupt?" - оно тоже в err логе?

**Comment by RoLex** [comment]
Вижу откуда летит сообщение > https://github.com/maxmind/geoip-api-c/blob/master/libGeoIP/GeoIP.c#L1421

Расшарь файл плиз.

**Comment by sirtrifanoff** [comment]
https://pastebin.com/GvJHiT9q

**Comment by RoLex** [comment]
Это последняя версия базы. У меня не падает но сообщение появляется. На выходных буду дальше смотреть.

**Comment by sirtrifanoff** [comment]
сделал тест на другом хабе. не повторилось падение. но заметил кое что еще. по !reload обновляется только город, страна не обновляется до ребута. проверял так: удалил базы maxmind в /usr/share/GeoIP, ребутнул верли, убедился что страна и город показывает пусто. сделал vh -g убедился что файлы баз в /usr/share/GeoIP появились. сделал !reload перезашел на хаб и увидел что город показывает, а страну нет. ребутнул хаб, появилась и страна и город.

**Comment by RoLex** [comment]
Пока не получается решить проблему. Попросил помощи у сотрудников по цеху и вернул код обратно. Будем подождать.

**Comment by RoLex** [comment]
Fixed in version `1.1.0.0`.
