### ISSUE TITLE
!ledohelp

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/ledokol#8]
Не работает для 3 класса, если  [::] autosendhelp = 0
Если  [::] autosendhelp = 1 то приходит, но только для ".:: Команды Ledokol для пользователей:"

Так же классу 3 недоступны команды заглушки по ip и я не нашел как бы я мог это разрешить.
Если возможно добавь пожалуйста возможность выбора класса для заглушек по ip

**Comment by RoLex** [comment]
mincommandclass - минимальный класс для использования операторских комманд.
minusrcommandclass - минимальный класс для использования комманд обычным юзером.

**Comment by sirtrifanoff** [comment]
Точно, оно. Почему то стояло mincommandclass 4. Спасибо.

**Comment by RoLex** [comment]
Потому что 4 по умолчанию.

**Comment by sirtrifanoff** [comment]
Я наверное чего-то недопонимаю, но если у оператора класс 3 то почему 
"mincommandclass - минимальный класс для использования операторских комманд." по умолчанию  4....
