### ISSUE TITLE
Вернулась старая проблема

### ISSUE THREAD

**Issue by sirtrifanoff** [Verlihub/ledokol#9]
Описанная и исправленная тут https://github.com/Verlihub/ledokol/issues/3

**Comment by RoLex** [comment]
```
[18:59:45] <# Feed> [10] Tester with IP 1.2.3.4.XX and class 2 used following command: !kick ohio Test
[18:59:45] <# Feed> [03] ohio with IP 2.3.4.5.YY and class 0 kicked: <# Test> Test
```

**Comment by sirtrifanoff** [comment]
Ну правильно, как и описано в https://github.com/Verlihub/ledokol/issues/3
должно же быть Tester а не <# Test>  [18:59:45] <# Feed> [03] ohio with IP 2.3.4.5.YY and class 0 kicked: <# Test> Test

**Comment by RoLex** [comment]
Так бот кикает юзера, а не вип, потому что у випа нет прав. Зачем тогда я добавлял оповещение? Если тебе больше нечего делать как нагружать меня всяким мусором, иди уберись у себя в квартире лучше.

**Comment by sirtrifanoff** [comment]
` [::] enablevipkick = 1` - ну нет прав на кик, так нет.
Оповещение которое ты добавил было о показе вводимой команды випом, а именно кик.

Я же говорю о
`если кикает вип то <бот> [02] Пользователь ёунигаз с IP-адресом 95.26.184.98.RU 0-го класса был кикнут: <бот> Нет указанных причин
если кикает оператор то <бот> [02] Пользователь март с IP-адресом 5.44.169.188.RU 0-го класса был кикнут: <никоператора> Нет указанных причин` - Это я скопировал из той ишуйки.

Хотя, если сЭр занят уборкой квартиры, то не буду отвлекать.

**Comment by RoLex** [comment]
У юзеров класса ниже 3 нет прав на кик других юзеров, потому в ледо имеется имитация кика для випов, которая позволяет им якобы использовать команду кика, на самом деле выполняя ее от имени бота т.к. у бота 10 класс и у него всегда есть права на кик юзеров.

Что касается оповещения - это глобальный вызов `VH_OnOperatorKicks`, который зовется вне зависимости от функции выполняющей сам кик, будь это команда в чат или протокольная команда, либо кик из другого скрипта. Если там был указан ник бота то будет показывать ник бота.

Что касается прав на кик для юзеров класса ниже 3 - в верли есть такое право, вот выписка из помощи:

```
!maykick <nick> [time]			- Allow user to kick users
```

Прежде чем нести херню, разберись как оно работает, а не ебашь посты по каждой мелочи. Я тебе не однократно говорил что мне осточертел твой бесконечный мусор - в нем только 20% реальных проблем.

**Comment by sirtrifanoff** [comment]
Вот теперь понятно. Если бы разбирался как "оно" работает, я бы свое что то пилил, либо pr строчил. Из мелочей как раз и складывается общее впечатление о продукте. Насчет бесконечно мелкого мусора, ты сам на каждом углу говоришь что пилишь верли для пользователей. Понятно что и с "бесконечным мусором" можно работать, но мне например лично что глаз режет о том я и пишу. Мне кажется проще объяснить, почему тот или иной случай невозможен, а не истерить.

**Comment by RoLex** [comment]
Хм, свое чтото пилил. Ты не KCAHDEP разве?

**Comment by sirtrifanoff** [comment]
я ксандер. и я сказал что. если бы понимал верли то PR бы пилил
